name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: opensuse/leap:15.5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.4.0

      - name: Set up Go 1.22
        uses: actions/setup-go@v4.2.0
        with:
          go-version: '1.22'

      - name: Download Go modules
        run: go mod download

      - name: Cache Go modules
        uses: actions/cache@v3.5.0
        with:
          path: |
            ~/.cache/go-build
            ${{ env.GOPATH }}/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Build Linux binaries
        env:
          CGO_ENABLED: '0'
          GOOS: linux
        run: |
          mkdir -p dist
          for arch in amd64 arm64; do
            go build \
              -ldflags "-X 'github.com/sarus-suite/parallax/version.Version=${{ github.ref_name }}'" \
              -o dist/parallax-${{ github.ref_name }}-linux-$arch \
              .
          done

      - name: Create GitHub Release
        id: release
        uses: actions/create-release@v1.1.0
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload amd64 binary
        uses: actions/upload-release-asset@v1.1.0
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: dist/parallax-${{ github.ref_name }}-linux-amd64
          asset_name: parallax-${{ github.ref_name }}-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload arm64 binary
        uses: actions/upload-release-asset@v1.1.0
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: dist/parallax-${{ github.ref_name }}-linux-arm64
          asset_name: parallax-${{ github.ref_name }}-linux-arm64
          asset_content_type: application/octet-stream

