name: Release opensuse amd64

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  actions: write
  attestations: write
  packages: read


jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/sarus-suite/parallax/ci-runner:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dump GO env
        run: |
          echo "--- all GO* vars ---"
          env | grep '^GO' || true
          echo "--- go env ---"
          go env

      - name: Install go deps
        run: go get .

      - name: Build Linux binaries
        env:
          CGO_ENABLED: "1"
          CC: gcc
          GOOS: linux
          GOFLAGS: "-buildvcs=false"
          GO_LDFLAGS: "-linkmode external"
          CGO_LDFLAGS: "-g -O2"
        run: |
          mkdir -p dist
          for arch in amd64; do
            GOARCH=$arch go build -v -x \
              -ldflags "-X 'github.com/sarus-suite/parallax/version.Version=${{ github.ref_name }}'" \
              -o dist/parallax-${{ github.ref_name }}-opensuse-15.5-$arch \
              .
          done

      - name: Inspect binary
        run: |
          file dist/parallax-${{ github.ref_name }}-opensuse-15.5-amd64
          readelf -l dist/parallax-${{ github.ref_name }}-opensuse-15.5-amd64 | grep interpreter || true
          ldd dist/parallax-${{ github.ref_name }}-opensuse-15.5-amd64 || echo "static :/"

      - name: Create or Update GitHub Release and Upload Asset
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: dist/parallax-${{ github.ref_name }}-opensuse-15.5-*
          allowUpdates: true
          replacesArtifacts: false
          draft: false
          prerelease: false

